export const WORKORA_ERROR_CODES = Object.freeze({
  UNKNOWN: "WORKORA_UNKNOWN",
  CONFIGURATION: "WORKORA_CONFIGURATION",
  VALIDATION: "WORKORA_VALIDATION",
  AUTHENTICATION: "WORKORA_AUTHENTICATION",
  AUTHORIZATION: "WORKORA_AUTHORIZATION",
  NOT_FOUND: "WORKORA_NOT_FOUND",
  CONFLICT: "WORKORA_CONFLICT",
  INTERNAL: "WORKORA_INTERNAL"
});

export type WorkoraErrorCode = typeof WORKORA_ERROR_CODES[keyof typeof WORKORA_ERROR_CODES];
